name: json_to_dart_model_plus
description: "A Dart package for generating Dart model code from JSON."
version: 0.0.9
homepage: https://github.com/mskayali/dartModelGenerator

environment:
  sdk: ">=2.19.6 <4.0.0"
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0 # For unit testing Dart code

# Optionally, add any Dart-only dependencies as needed, such as for HTTP requests, JSON handling, etc.
